### ISSUE TITLE
Deferred deep link is empty when install the app

### ISSUE THREAD

**Issue by NikitaKoltsov** [BranchMetrics/ios-branch-deep-linking-attribution#936] opened 2019-09-11 10:38 UTC
I have a problem with deferred deep links when we tap on a link and the app is not installed.
DeepLinkHandler closure returns `["+is_first_session"): 1, "+clicked_branch_link": 0]`after I install the app.
If I tap on the same link and I've already installed the app - It works as expected and returns deep link info.

To test deferred deep linking I do:
- remove the app from device
- select link in Notes app
- it asks to navigate to AppStore, I proceed
- launch the app from XCode

I've tried those things:
- launch with both test and live keys and domains
- checked validateSDKIntegration - all is okay
- tried to add and remove setUseTestBranchKey

My code in AppDelegate 
didFinishLaunchingWithOptions:
```
Branch.getInstance()?.initSession(launchOptions: launchOptions,
                                      andRegisterDeepLinkHandler:
      { [weak self] (params, error) in
        print("Branch parameters: \(params)")
        
        if let urlString = params?[BranchConstants.deepLinkKey] as? String,
          let deepLink = AppURLQuery.deepLink(from: urlString) {
          self?.handleDeepLink(AppURLQuery.deepLink(from: url))
        } 
    })
```

continue userActivity:
```
Branch.getInstance()?.continue(userActivity)
```

open url:
```
Branch.getInstance()?.application(app, open: url, options: options)
```

**Comment by tomerciucran** [comment] 2019-10-23 10:02
Same issue here.

**Comment by shial4** [comment] 2019-11-29 01:18
same issue here, Pod version 0.30.0 introduced it. 
callback andRegisterDeepLinkHandler not received after fresh install.

**Comment by echo-branch** [comment] 2019-12-06 02:38
@shial4 
The 0.30 release was intended to address issues like this.  So let's figure out why you started seeing it from that version.

1. Are you testing with iPadOS (iOS 13+ on iPad)?  There's a known server side issue with deferred deeplinks that's being worked on.
2. Are you testing with Chrome?  There's a known server side issue with iOS Chrome that's being worked on.
3. Are you getting no callback or a callback with no link params?

**Comment by shial4** [comment] 2019-12-06 03:01
Hi @echo-branch 

Ad 1. I am testing with iPhone. iOS 12+ & 13+
Ad 2. I'm testing with safari, have not tested with chrome. 
Ad 3. I am not getting initial callback at all. 

My steps are:
1. Open link in safari 
2. Navigate to AppStore from webpage 
3. Install App (fresh install)
4. Launch the app.

Result: Call back isn't received, however, If I kill the app & open it again it is deliver on second app open. 

It's working fine with previous version of SDK. < 0.30.0

**Comment by echo-branch** [comment] 2019-12-06 23:01
@shial4 
Ok that eliminates some possibilities.  

1.  Are you able to provide a debug log?  I want to see if we make a request for data on first run.
2.  Could you provide what your branch initSession code looks like?  Such as where is it called from and is there a delay?

**Comment by shial4** [comment] 2019-12-08 22:56
We do it in 

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`

The implementation looks like: 

```
 if let branch = Branch.getInstance() {
            branch.registerFacebookDeepLinkingClass(FBSDKAppLinkUtility.self)
            branch.suppressWarningLogs()
            branch.delayInitToCheckForSearchAds()
            branch.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in
                if error == nil {
                    // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
                    // params will be empty if no data found
                    
                    if let params = params {
                        if  let iosUrl = self.branchUrlParams.filter({item in params[item] != nil}).map({item in params[item]}).first as? String, let deepLinkUrl = URL(string: iosUrl){
                            if DeeplinkHandler.shared.canHandleDeeplink(withUrl: deepLinkUrl) {
                                DeeplinkHandler.shared.handleDeeplink(withUrl: deepLinkUrl)
                                return
                            }
                        }
                        DeepLinker.shared.handleDeepLinking(params)
                    }
                    
                    if let params = params as? [String: AnyObject] {
                        print("params: %@", params)
                    }
                }
            })
        }
```

Might be able to provide it later.  I will rebuild it with 0.30.0 and reproduce the flow then will post it here.

**Comment by echo-branch** [comment] 2019-12-18 01:13
Found an edge case that causes first payload failure on first install, it could be the case you're running into.  See if 0.31.1 resolves it for you.

**Comment by shial4** [comment] 2020-01-24 01:13
version: **0.31.3**

It is not fixed. Initial callback is not delivered. Same as it was before. I kill the app open again and callback is present. 

I did notice that with previous **(0.29.3)** version **(which is working for us)**
sometimes the `andRegisterDeepLinkHandler` callback is delivered with delay. This is breaking our flow for new users as we do not know if they were referred by someone. As a result we have a lot of support tickets due to lack of granted points for refereeing.

**Comment by Heinemark** [comment] 2020-02-18 21:11
Had this issue too in latest SDK version and after some debugging I found that calling `Branch setIdentity:` before the SDK is initialised (how do I know when it is?) stops `andRegisterDeepLinkHandler:` from being called. 

The problem is that `initUserSessionAndCallCallback:` is called with `NO` so no callback will happen

```
// SDK-631 Workaround to maintain existing error handling behavior.
// Some methods require init before they are called.  Instead of returning an error, we try to fix the situation by calling init ourselves.
// There is a follow up ticket to improve this.  SDK-633
- (void)initSafetyCheck {
    if (self.initializationStatus == BNCInitStatusUninitialized) {
        BNCLogDebug(@"Branch avoided an error by preemptively initializing.");
        [self initUserSessionAndCallCallback:NO];
    }
}
```

**Comment by shial4** [comment] 2020-03-12 01:56
It seem like version `0.31.4` Have solved the problem :)

**Comment by DmitryShapovalov** [comment] 2020-04-01 15:55
Same issue here.

**Comment by doanduchieu** [comment] 2020-04-20 10:37
> 2. Are you testing with Chrome? There's a known server side issue with iOS Chrome that's being worked on.

Hi @echo-branch, I still see the issue that you mentioned above. Where can I follow this issue?

**Comment by echo-branch** [comment] 2020-04-20 16:42
@doanduchieu 
There's a new chrome deferred deeplink issue being worked on internally.  Please open a new ticket I can keep that one updated for visibility.

I should have closed this particular thread since it's a different root cause.

**Closed by echo-branch** 2020-04-20 16:42 UTC

**Comment by crash481** [comment] 2021-03-17 19:04
> Had a similar issue in latest SDK version and after some debugging I found that calling `Branch setIdentity:` before the SDK is initialised stops `andRegisterDeepLinkHandler:` from being called.
> 
> The problem is that `initUserSessionAndCallCallback:` is called with `NO` so no callback will happen
> 
> ```
> // SDK-631 Workaround to maintain existing error handling behavior.
> // Some methods require init before they are called.  Instead of returning an error, we try to fix the situation by calling init ourselves.
> // There is a follow up ticket to improve this.  SDK-633
> - (void)initSafetyCheck {
>     if (self.initializationStatus == BNCInitStatusUninitialized) {
>         BNCLogDebug(@"Branch avoided an error by preemptively initializing.");
>         [self initUserSessionAndCallCallback:NO];
>     }
> }
> ```

Whoa, this is great answer, why Branch do not have this in documentation?

**Comment by echo-branch** [comment] 2021-03-17 19:41
@crash481 Sorry about the confusion.  That should have been written more clearly, the intent is that setIdentity is called after initSession completes, not right after it on the next line. I'll ask to docs team to clarify it.

**Comment by theappletalks** [comment] 2022-12-17 16:05
Hi Everyone,
I've found the solution to this problem; I've been working on it for a week and I've finally figured it out.

It appears that the branch's initialization takes time on the first launch, so calling the init session immediately after creating the branch's object will not work.
Here's my snippet fix for this

**Init branch**
```
Branch.setUseTestBranchKey(false)
        let branch: Branch = Branch.getInstance()
        branch.enableLogging()
    
      ### This is the fix and most important point.
       // If this is first app launch, then add delay of 2 seconds because branch needs some time to process the data.
        if application.isFirstLaunch(){
            self.delay(time: 2.0) { **Adding delay**
                self.configureBranch(launchOptions: launchOptions) **Calling function to init session**
            }
        }else{
            configureBranch(launchOptions: launchOptions) **Calling function to init session**
        }
        
    func configureBranch(launchOptions:[UIApplication.LaunchOptionsKey: Any]?){
        Branch.getInstance().initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: {params, error in
            print("branchParam:\(params ?? [:])")
            **Do what ever you wish with params.**
            
            **Resetting branch session as it was not being cleared for next launch**
            Branch.getInstance().resetUserSession()
        })
    }
```

Above is fixed and tested today and it's working absolutely fine. Branch should have identified and added it on their documents.

I am also a YouTuber, and I would love it if you could just subscribe to my channel:
http://youtube.com/@appletalks

Thank you!

**Comment by korolkir** [comment] 2023-12-20 13:48
Hello @NikitaKoltsov @shial4 Were you able to find a resolution for this issue? I'm experience exactly the same problem with the latest library version
