### ISSUE TITLE
Status 400 when opening Universal Link

### ISSUE THREAD

**Issue by davemess** [BranchMetrics/ios-branch-deep-linking-attribution#969] opened 2019-11-19 21:49 UTC
I'm getting an error from the BranchSDK when opening a Universal Link:

```
Error: An error prevented request to https://api2.branch.io/v1/open from completing: Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}
```

Also seeing this in the logs:

```
Server returned: Status: 400; Data: {
    error =     {
        instrumentation =         (
        );
        "link_identifier" = "doesn't pass regex";
    };
}
```

Not sure what the `link_identifier` is and how to fix it.

**Comment by echo-branch** [comment] 2019-11-19 21:58
@davemess 
That's a Branch internal value used to match clicks.  Could you send me a sample URL and repro steps?

Are you using URL fragments with FB?  We have a backlogged bug where FB added params would split our link id and cause a failure similar to that one.

**Comment by davemess** [comment] 2019-11-19 22:25
Here's an example url generated from our app: https://t.vrbo.io/hmNSPSe9I1

**Comment by echo-branch** [comment] 2019-11-20 00:29
Filed a ticket to look into this one.

**Comment by derrick-branch** [comment] 2020-03-04 22:36
@davemess can you turn on setDebug and send us the entire request body via logs? We're probably flagging one of the key-value pairs built into this link. 

We'll use the request to reproduce, then look up the regex in place for your app (based on the branch_key in the request). Then we'll be able to tell you exactly why this link is getting flagged.

Really sorry for the slow response! Want to close the loop here.

**Comment by davemess** [comment] 2020-03-05 16:46
Unfortunately we have decided to remove Branch functionality.

**Comment by derrick-branch** [comment] 2020-03-05 17:10
Ah okay. I'm sorry to hear that. If you do want to explore this further, let us know. For now will close this.

**Closed by derrick-branch** 2020-03-05 17:10 UTC

**Comment by derrick-branch** [comment] 2020-03-05 18:06
@davemess FYI, I'm not able to reproduce when using this link either with your live branch_key or test branch_key. The link is associated with your test branch_key and returns data. 

Again, sounds like you don't need to pursue this future, but if you do, please re-open.
