### ISSUE TITLE
Git repository is very large, takes a long time to fetch using Xcode + Swift Package Manager

### ISSUE THREAD

**Issue by JonathanDowning** [BranchMetrics/ios-branch-deep-linking-attribution#1053] opened 2020-08-24 22:01 UTC
I was really excited to see Branch now supports SPM as of 0.35.0, however I noticed it now takes an awfully long time to resolve my dependencies.

Upon further inspection it looks like the repo is >750MB in size, owing to including binary frameworks inside the repository.

Xcode for some reason chooses to fetch the entire directory and therefore it takes an inordinate amount of time to download (over 7 minutes). 
<img width="567" alt="Screen Shot 2020-08-24 at 2 55 43 PM" src="https://user-images.githubusercontent.com/2230175/91100659-78e47e00-e61a-11ea-8999-b578f3671811.png">

I'm not entirely sure what the solution is to this, but I wanted to raise the issue to hopefully stimulate a discussion.

If this repo was starting again I would respectfully suggest including binary frameworks in the releases section of the GitHub site, as opposed to including them in the repo itself. I realize this isn't an ideal solution now the repo has grown to this size. Hopefully someone has a good solution to this issue.

**Comment by echo-branch** [comment] 2020-08-24 22:03
@JonathanDowning 
Aware of the issue, however editing git history is probably a poor choice.  Will need to evaluate our options.

**Comment by kaomte** [comment] 2021-01-02 20:34
I am also experiencing this. I often am not working with super fast internet connections and this really puts a damper on development.

**Comment by ragzy15** [comment] 2021-01-21 13:42
@echo-branch is there any update regarding this problem?

**Comment by echo-branch** [comment] 2021-01-21 17:11
Not yet. I haven't found a simple solution to this issue. As of right now, I think we may need to create a fresh repo without the bloat from historical release binaries.

**Comment by acefsm** [comment] 2021-02-10 19:39
1. git gc --prune=now --aggressive
    726.8 MB -> 564.8 MB
2. delete old merged branches
    https://nickymeuleman.netlify.app/blog/delete-git-branches
    https://railsware.com/blog/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/

**Comment by echo-branch** [comment] 2021-02-11 01:39
@acefsm
That's a good idea to bring it to a slightly more reasonable 560mb in the short term.

**Comment by kristohear** [comment] 2021-03-19 17:01
i think this should get more notice, in our CI machine 50% of build time goes under the Branch SPM.
I would like to have the fresh repo for SPM, maybe in the beginning just keep it up to date with releases only?

**Comment by andreyz** [comment] 2021-03-19 17:28
What about moving all binaries to Git-LFS? I agree this is a shamefully overlooked issue, that's slowing down anyone using Branch via SPM.

**Comment by echo-branch** [comment] 2021-03-19 18:09
@andreyz
We've already removed the binaries, they're in history so switching over now won't help. The more I look at this, the more I think we need a new repo for just SPM. Unless Apple gifts us the ability to use shallow clones.

**Comment by paigeyahnke** [comment] 2021-04-13 18:55
> The more I look at this, the more I think we need a new repo for just SPM

@echo-branch 
Hello, I'm wondering if this is somewhere on the roadmap? We recently added the branch SDK to our app and this has already become a significant hinderance to development.

**Comment by ragzy15** [comment] 2021-04-27 10:17
@echo-branch can you provide some timeline regarding this issue?

**Comment by dmiluski** [comment] 2021-04-27 16:31
We recently onboarded a new developer from Canada, and found that both Branch (750 MB) as well as [Intercom](https://github.com/intercom/intercom-ios) being even worse with (1.5GB) could prevent installing dependencies as the large size could time out if not on a very fast network.

Yes, this is a learning lesson. Revealed with the evolution of tools. So I'm thankful for any option that could help.

I would be very thankful if we could shift to a new repo without the heavy size.

**Comment by kristohear** [comment] 2021-05-26 21:14
@echo-branch is it possible to get the new repo as soon as possible? Its really frustrating to work with branch ios sdk at the moment.

**Comment by dmiluski** [comment] 2021-06-07 21:09
@echo-branch 
Adding a weekly/monthly reminder that having a bloated repo is extremely painful as a consuming developer/app. I can attest that having bloated SPM repos is preventing high latency Canadian developers from being able to quickly switch branches and contribute code. Often failing without being able to get setup and running resulting in significant frustration. 

Bloated repos integrated with SPM lead to:
- Additional clone time on CI
- Additional build time after switching branches

This extra time adds to flakey build behaviors, the compound per developer, per branch, per build, leading to general build frustration.

**Comment by jdee** [comment] 2021-06-12 02:47
We're preparing a new repo to address this. First getting GitHub Actions properly set up here to automate the process. Stay tuned, and sorry for the long delay.

Any opinions on repo names? I'm not including any variant of "branch" in a repo scoped to BranchMetrics. Working with `ios-spm` for now, i.e. `BranchMetrics/ios-spm`. Less typing! :tada:

**Comment by jdee** [comment] 2021-06-15 16:53
Please try https://github.com/BranchMetrics/ios-spm with Swift Package Manager. Please report any issues with that integration in either repo. All comment on the PR and solution welcome.

**Comment by jdee** [comment] 2021-06-15 16:57
https://help.branch.io/developers-hub/docs/ios-basic-integration#via-swift-package-manager

**Comment by jdee** [comment] 2021-06-16 00:41
Also relevant: https://github.com/SwiftPackageIndex/PackageList/pull/1171

**Comment by paigeyahnke** [comment] 2021-06-18 18:45
Just wanted to leave a comment saying thank you. Switched to the new repo today and clone times were **dramatically** improved. 🎉

**Comment by jdee** [comment] 2021-06-19 00:29
I'm glad this helped.

I finally found my way through the process in Xcode 13 beta and updated the docs. https://help.branch.io/developers-hub/docs/ios-basic-integration#via-swift-package-manager

We are also now in the [Swift Package Index](https://swiftpackageindex.com/BranchMetrics/ios-spm).

We'll merge the automation PR next week and close this issue.

**Comment by dmiluski** [comment] 2021-06-22 21:19
Semi feedback:
Just switched, while it is much faster, the packages isn't name very obvious to understand what it it is? Perhaps renamed to be branch?

![Screen Shot 2021-06-22 at 2 18 53 PM](https://user-images.githubusercontent.com/5083390/123000749-d2195d00-d364-11eb-8b0c-19ef0b08476a.png)

**Comment by jdee** [comment] 2021-06-22 21:32
Thanks for that feedback, @dmiluski. Minor points are important too. I also noticed that issue. I do think we could rename the repo without much effort. GitHub will redirect, and probably not many people are using it yet.

The problem is that SPM just uses the `repo` part of the GitHub `org/repo`. It's hard to have this repo just be called `BranchMetrics/Branch`. The package it includes is just called `Branch`. 

<img width="1662" alt="8b77e12-Screen_Shot_2021-06-18_at_5 12 26_PM (1)" src="https://user-images.githubusercontent.com/121951/123002164-7354e300-d366-11eb-923a-3306515ead06.png">

Given that it's scoped to `BranchMetrics`, in the same namespace with all our other public and private repos for a host of purposes and platforms, it should probably include `ios`, `spm` or `swift-package-manager` to distinguish it from the main repo. Maybe `ios-branch-sdk-spm` or something?

As soon as SPM supports shallow cloning or a better option, we'll ask everyone to revert to the main repo and hope to shut the other one down (much later). So I expect the `ios-spm` repo is not a permanent solution anyway.

**Comment by jdee** [comment] 2021-07-01 17:08
We've renamed the new repo to `ios-branch-sdk-spm`. The docs have been updated. https://help.branch.io/developers-hub/docs/ios-basic-integration#via-swift-package-manager

Closing this issue. The last automation task is a separate matter.

**Closed by jdee** 2021-07-01 17:08 UTC

**Comment by JonathanDowning** [comment] 2021-07-01 17:20
Thank you for your work on this! I appreciate it :)
