### ISSUE TITLE
Deprecated API usage warnings for iOS 12+

### ISSUE THREAD

**Issue by hipwelljo** [BranchMetrics/ios-branch-deep-linking-attribution#1062] opened 2020-10-02 19:18 UTC
Using version 0.35.0 in Xcode 12, there are 10 warnings shown due to deprecated API use. subscriberCellularProvider, archivedDataWithRootObject, and unarchiveObjectWithData. Note that Xcode 12 warns you should update the minimum deployment target to iOS 12.

**Comment by echo-branch** [comment] 2021-02-11 01:35
We have a ticket for this in the backlog. At present, we maintain support for all versions of iOS that Xcode 12 supports (iOS 9+) which complicates coming up with a clean fix for this.

**Comment by bdrelling** [comment] 2021-04-28 18:23
@echo-branch is there any updated status to this? What sort of solutions is Branch considering? We'd like to see this resolved so we can remove the issues from our console caused by the Branch SDK. Is it more complicated than just using `@available` and `#available` where necessary?

**Comment by echo-branch** [comment] 2021-04-28 18:32
@bdrelling 
It is more complex than that, but we are working on it now. The available check will make sure we use the correct API, however it does not suppress deprecated warnings due to the old code being present in the else block.

I personally don't like suppressing warnings, so we're looking at using macros to exclude the old code when using a newer version. Not really sure that will be nicer than just suppressing warnings in the old code block.

**Closed** 2022-06-03 18:25 UTC
